package com.mobilerag.spikes

import android.content.Context
import com.mobilerag.hebbian.Arme
import com.mobilerag.hebbian.HippocampalGnn
import com.mobilerag.hebbian.TypeProfiles
import com.mobilerag.hebbian.computeETQuadrant
import kotlin.math.abs

/**
 * Hebbian math golden-value spike: replays the exact deterministic scenario from
 * docs/hebbian-golden-values.txt through the Kotlin ports (Arme, HippocampalGnn,
 * TypeProfiles) and asserts every printed value within 1e-5.
 *
 * The golden file was generated by running the ORIGINAL Python torch modules
 * (core/arme_v2.py, hippocampal_gnn_pyg.py, type_profiles.py) on fixed inputs —
 * 4-node/3-edge graph, two ARME steps with VAD overrides and an injected clock
 * (t = 1_700_000_000 then +60 s), propagate, two modulated_hebbian_update cases,
 * and the type-profile functions. Python computes in float32 while the port uses
 * Double, so per the file's own note the tolerance is 1e-5, not exact equality.
 * No models, no store, no RNG.
 */
class HebbianMathSpike : Spike {
    override val id = "hebbian_math"
    override val title = "Hebbian math golden values"
    override val description = "Replays docs/hebbian-golden-values.txt (Python torch reference) through the Kotlin Arme/HippocampalGnn/TypeProfiles; every value asserted within 1e-5."

    override suspend fun run(context: Context, log: (String) -> Unit): SpikeResult {
        return try {
            var nPass = 0
            val failures = mutableListOf<String>()

            fun report(ok: Boolean, line: String) {
                if (!ok) failures += line.substringBefore("  actual=").trim()
                log("%-4s %s".format(if (ok) "PASS" else "FAIL", line))
                if (ok) nPass++
            }

            fun checkNum(name: String, actual: Double, expected: Double, tol: Double = 1e-5) =
                report(abs(actual - expected) <= tol, "$name  actual=%.8f expected=%.8f".format(actual, expected))

            fun checkStr(name: String, actual: String, expected: String) =
                report(actual == expected, "$name  actual=%s expected=%s".format(actual, expected))

            fun checkInt(name: String, actual: Int, expected: Int) =
                report(actual == expected, "$name  actual=%d expected=%d".format(actual, expected))

            // ── Fixed inputs (golden file "=== inputs ===") ─────────────
            val h = arrayOf(
                floatArrayOf(0.05241424f, 0.05241424f, 0.99587059f, 0.05241424f),
                floatArrayOf(0.05504819f, 0.11009638f, 0.99086738f, 0.05504819f),
                floatArrayOf(0.50000000f, 0.50000000f, 0.50000000f, 0.50000000f),
                floatArrayOf(0.99587059f, 0.05241424f, 0.05241424f, 0.05241424f),
            )
            val edgeSrc = intArrayOf(0, 1, 2)
            val edgeDst = intArrayOf(1, 2, 3)
            val edgeW = doubleArrayOf(1.0, 0.8, 1.2)

            // ── compute_e_t_quadrant ────────────────────────────────────
            log("── compute_e_t_quadrant ──")
            val quadrants = listOf(
                ETCase("Q1", 0.6, 0.8, 0.59151940),
                ETCase("Q4", 0.6, 0.2, 0.37994896),
                ETCase("Q2", -0.7, 0.8, -0.50381065),
                ETCase("Q3", -0.4, 0.2, -0.21728043),
            )
            for ((qName, v, a, expectedET) in quadrants) {
                val st = computeETQuadrant(v, a)
                checkStr("e_t $qName quadrant", st.quadrant, qName)
                checkNum("e_t $qName", st.eT, expectedET)
            }

            // ── Two ARME steps with injected clock ──────────────────────
            // Golden generator: q = [0.10, 0.05, 0.90, 0.05], retrieved = H[:3],
            // scores = [0.9, 0.7, 0.5], node_A with node_activations=1,
            // total_activations=5, time patched to T0 then T0+60.
            val t0 = 1_700_000_000.0
            var now = t0
            val arme = Arme(timeNowS = { now })
            val q = floatArrayOf(0.10f, 0.05f, 0.90f, 0.05f)
            val retrieved = h.copyOfRange(0, 3)
            val scores = doubleArrayOf(0.9, 0.7, 0.5)

            log("── arme step 1 (Q1, first sight of node_A) ──")
            val (mT1, s1) = arme.step(
                queryEmb = q, retrievedEmbs = retrieved, userText = "ignored (overrides)",
                nodeId = "node_A", nodeActivations = 1, totalActivations = 5,
                retrievalScores = scores,
                valenceOverride = 0.6, arousalOverride = 0.8, dominanceOverride = 0.7,
            )
            checkNum("step1 r_t", s1.rT, 0.70642495)
            checkNum("step1 u_t", s1.uT, 0.20000000)
            checkNum("step1 delta_t", s1.deltaT, 1.00000000)
            checkStr("step1 quadrant", s1.emotion.quadrant, "Q1")
            checkNum("step1 e_t", s1.emotion.eT, 0.59151940)
            checkNum("step1 dominance", s1.dominance, 0.70000000)
            checkNum("step1 s_t", s1.sT, 0.82046276)
            checkNum("step1 m_t_raw", s1.mTRaw, 2.27155078)
            checkNum("step1 m_t", mT1, 1.50862031)
            checkStr("step1 gated", s1.gated.toString(), "false")

            log("── arme step 2 (Q2, same node 60 s later) ──")
            now = t0 + 60.0
            val (mT2, s2) = arme.step(
                queryEmb = q, retrievedEmbs = retrieved, userText = "ignored (overrides)",
                nodeId = "node_A", nodeActivations = 1, totalActivations = 5,
                retrievalScores = scores,
                valenceOverride = -0.7, arousalOverride = 0.8, dominanceOverride = 0.3,
            )
            checkNum("step2 r_t", s2.rT, 0.70642495)
            checkNum("step2 u_t", s2.uT, 0.20000000)
            checkNum("step2 delta_t", s2.deltaT, 0.18126925)
            checkStr("step2 quadrant", s2.emotion.quadrant, "Q2")
            checkNum("step2 e_t", s2.emotion.eT, -0.50381065)
            checkNum("step2 dominance", s2.dominance, 0.30000000)
            checkNum("step2 s_t", s2.sT, -0.11766928)
            checkNum("step2 m_t_raw", s2.mTRaw, 0.88899001)
            checkNum("step2 m_t", mT2, 1.26076819)
            checkStr("step2 gated", s2.gated.toString(), "false")

            // ── propagate (H_post) ──────────────────────────────────────
            log("── propagate output (H_post) ──")
            val hPost = HippocampalGnn.propagate(h, edgeSrc, edgeDst, edgeW)
            val expectedPost = arrayOf(
                doubleArrayOf(0.00000000, 0.00000000, 0.00000000, 0.00000000),
                doubleArrayOf(0.05236630, 0.05236630, 0.75985444, 0.05236630),
                doubleArrayOf(0.04401011, 0.08785006, 0.65993243, 0.04401011),
                doubleArrayOf(0.46211717, 0.46211717, 0.46211717, 0.46211717),
            )
            for (r in 0 until 4) for (c in 0 until 4) {
                checkNum("H_post[$r][$c]", hPost[r][c].toDouble(), expectedPost[r][c])
            }

            // ── modulated_hebbian_update, m_t from step 1 ───────────────
            log("── modulated_hebbian_update (m_t from step 1) ──")
            val lamOja = doubleArrayOf(0.008, 0.012, 0.008)
            val res1 = arme.modulatedHebbianUpdate(
                edgeSrc = edgeSrc, edgeDst = edgeDst, edgeWeight = edgeW.copyOf(),
                hPost = hPost, mT = mT1, lamOja = lamOja,
                eligibility = doubleArrayOf(0.3, 0.1, 0.5),
            )
            val expW1 = doubleArrayOf(1.00000000, 0.83003861, 1.22265911)
            val expE1 = doubleArrayOf(0.24000001, 0.59066224, 0.78623879)
            for (i in 0 until 3) {
                checkNum("case1 new_w[$i]", res1.edgeWeight[i], expW1[i])
                checkNum("case1 elig_out[$i]", res1.eligibility[i], expE1[i])
            }
            checkInt("case1 n_eligible", res1.stats.nEligible, 3)
            checkInt("case1 n_total", res1.stats.nTotal, 3)
            checkNum("case1 mean_coact", res1.stats.meanCoact, 0.29896700)
            checkNum("case1 mean_w", res1.stats.meanW, 1.01756585)
            checkNum("case1 eligible_mean_w", res1.stats.eligibleMeanW, 1.01756585)
            checkNum("case1 ineligible_mean_w", res1.stats.ineligibleMeanW, 0.00000000)

            // ── modulated_hebbian_update, m_t from step 2, zero traces ──
            log("── modulated_hebbian_update (m_t from step 2, zero traces) ──")
            val res2 = arme.modulatedHebbianUpdate(
                edgeSrc = edgeSrc, edgeDst = edgeDst, edgeWeight = edgeW.copyOf(),
                hPost = hPost, mT = mT2, lamOja = lamOja,
                eligibility = DoubleArray(3),
            )
            val expW2 = doubleArrayOf(0.99699998, 0.82510352, 1.21893644)
            val expE2 = doubleArrayOf(0.00000000, 0.51066226, 0.38623875)
            for (i in 0 until 3) {
                checkNum("case2 new_w[$i]", res2.edgeWeight[i], expW2[i])
                checkNum("case2 elig_out[$i]", res2.eligibility[i], expE2[i])
            }
            checkInt("case2 n_eligible", res2.stats.nEligible, 2)
            checkInt("case2 n_total", res2.stats.nTotal, 3)
            checkNum("case2 mean_coact", res2.stats.meanCoact, 0.29896700)
            checkNum("case2 mean_w", res2.stats.meanW, 1.01367998)
            checkNum("case2 eligible_mean_w", res2.stats.eligibleMeanW, 1.02201998)
            checkNum("case2 ineligible_mean_w", res2.stats.ineligibleMeanW, 0.99699998)

            // ── type_profiles ───────────────────────────────────────────
            log("── type_profiles ──")
            checkNum("SECONDS_PER_DAY", TypeProfiles.SECONDS_PER_DAY, 86400.0)
            checkNum("vocabulary tau_stale_s", TypeProfiles.profileFor("vocabulary").tauStaleS, 172800.0)
            checkNum("vocabulary lam_mult", TypeProfiles.profileFor("vocabulary").lamMult, 1.5)
            checkNum("grammar tau_stale_s", TypeProfiles.profileFor("grammar").tauStaleS, 864000.0)
            checkNum("grammar lam_mult", TypeProfiles.profileFor("grammar").lamMult, 0.7)
            checkNum("event tau_stale_s", TypeProfiles.profileFor("event").tauStaleS, 129600.0)
            checkNum("event lam_mult", TypeProfiles.profileFor("event").lamMult, 1.5)
            checkNum("unknown_type tau_stale_s", TypeProfiles.profileFor("unknown_type").tauStaleS, 259200.0)
            checkNum("unknown_type lam_mult", TypeProfiles.profileFor("unknown_type").lamMult, 1.0)
            checkNum("staleness(86400, vocabulary)", TypeProfiles.staleness(86400.0, "vocabulary"), 0.39346934)
            checkNum("staleness(0, grammar)", TypeProfiles.staleness(0.0, "grammar"), 0.00000000)
            checkNum("lam_for(grammar, 0.008)", TypeProfiles.lamFor("grammar", 0.008), 0.00560000)
            checkNum("lam_for(task, 0.008)", TypeProfiles.lamFor("task", 0.008), 0.01280000)

            val total = nPass + failures.size
            val passed = failures.isEmpty()
            SpikeResult(
                passed = passed,
                summary = if (passed) "All $total golden values match within 1e-5"
                else "$nPass/$total match — FAILED: ${failures.take(8).joinToString()}",
                metrics = mapOf(
                    "checks" to "$nPass/$total",
                    "tolerance" to "1e-5",
                ),
            )
        } catch (t: Throwable) {
            SpikeResult(
                passed = false,
                summary = "Failed: ${t.javaClass.simpleName}: ${t.message?.take(200)}",
                error = t.stackTraceToString().take(2000),
            )
        }
    }

    private data class ETCase(val name: String, val v: Double, val a: Double, val eT: Double)
}
